#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Load secrets, not kept under version control
test -f "${HOME}/.secrets" && source "${HOME}/.secrets"

# Make vim the default editor.
export EDITOR='vim';

# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY_FILE=~/.node_history;
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';

# Prefer US English and use UTF-8.
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Always enable colored `grep` output.
export GREP_OPTIONS='--color=auto';

# Python
export WORKON_HOME=$HOME/.virtualenvs
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
export DJANGO_ENV=local
export PYTHONDONTWRITEBYTECODE=1
export NRUSER="Thomas Achtemichuk"

export PATH="/usr/local/opt/openssl/bin:/usr/local/opt/curl/bin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export LDFLAGS="-L/usr/local/opt/openssl/lib -L/usr/local/opt/curl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include -I/usr/local/opt/curl/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig"

# ALIASES

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && sudo killall -HUP mDNSResponder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en9' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en9 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"

# OS X has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# OS X has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Trim new lines and copy to clipboard
alias c="tr -d '\n' | pbcopy"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy="/usr/libexec/PlistBuddy"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	alias "$method"="lwp-request -m '$method'"
done

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume 7'"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"


alias pyc="find . -name '__pycache__' -o -name '*.pyc' | xargs rm -rf"
alias f="ag --py --ignore='*migration*'"
alias q="tail -f $TMPDIR/q"

alias bs='cd ~/src/bs; workon bs'

function s() {
  cd $(hg root -q 2> /dev/null || echo -n "$HOME/src/bs")
  workon bs
  ./project/manage.py shell_plus --quiet-load
}

function runserver() {
  sudo brew services stop nginx
  sudo brew services start nginx
  workon bs
  cd $(hg root -q 2> /dev/null || echo -n "$HOME/src/bs")
  ./project/manage.py runserver_plus --traceback
}

function celeryd() {
  workon bs
  cd $(hg root -q 2> /dev/null || echo -n "$HOME/src/bs")/project
  celery worker -A celery_worker -l DEBUG
}

alias stops="sudo brew services stop nginx; brew services stop mysql;  brew services stop elastic; brew services stop rabbit; brew services stop redis; brew services stop postgres; brew services stop memcached"
alias starts="sudo brew services start nginx; brew services start mysql; brew services start elastic; brew services start rabbit; brew services start redis; brew services start postgres; brew services start memcached"

## Find files matching pattern
function ff() {
    find . -iname "*$@*" | grep --color "$@"
}

function transcode() {
    nice -n 12 \
      ffmpeg \
        -y \
        -threads auto \
        -i "$1" \
        -strict experimental \
        -s 1920x1080 \
        -c:v libx264 \
        -crf 20 \
        -preset veryslow \
        -profile:v high \
        -level 4.0 \
        -tune film \
        -pix_fmt yuv420p \
        -c:a aac \
        -b:a 160k \
        -f mp4 \
        "$2"
}

function server() {
  qemu-system-x86_64 \
    -cpu host \
    -machine pc-q35-3.0,accel=hvf \
    -accel hvf,thread=multi \
    -m size=4G\
    -hda server.img \
    -cdrom ubuntu1804.iso \
    -netdev type=tap,ifname=tun0,script=/Users/thomas/.vm/qemu-ifup,downscript=no,id=net0 \
    -device e1000,netdev=net0,mac=a0:99:9b:09:be:99 \
    -runas thomas \

}
