# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

test -f /usr/local/share/zsh/site-functions/_awless && source /usr/local/share/zsh/site-functions/_awless
test -f "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
which virtualenvwrapper_lazy.sh 2>&1 > /dev/null && source `which virtualenvwrapper_lazy.sh`

unalias run-help > /dev/null 2>&1
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# KEY BINDINGS

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Same bindings as ~/.vimrc
bindkey -M vicmd 'j' down-line-or-beginning-search
bindkey -M vicmd 'k' up-line-or-beginning-search
# bindkey -M vicmd 'l' backwardk-char
# bindkey -M vicmd ';' forward-char

# allow v to edit the command line (standard behaviour)
autoload -Uz edit-command-line
bindkey -M vicmd 'v' edit-command-line

# Command + Arrow keys
bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line

# Alt + . to insert last argument
bindkey '\e.' insert-last-word
